### ISSUE TITLE
Add shells other than zsh

### ISSUE THREAD

**Issue by AMASENA** [ceuk/git-file-history#1]
OS: arch
install method: AUR (makepkg -sir)

I found this repo from your comment on reddit about zed editor (2 months ago) and said why not try it.

List view works fine, but when I choose a commit it says "zsh" executable file not found in $PATH

I don't know if you have the time to do this or not but thought I would make this just to give you a heads up about this I guess.

**Comment by ceuk** [comment]
Hey @AbdullahELBrawany this should be fixed in [0.0.5](https://github.com/ceuk/git-file-history/releases/tag/v0.0.5)
